#
# Bens zshrc managed in dotfiles
#


parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}



aws-set-env() {
    # Check if exactly one argument is provided
    if [ "$#" -ne 1 ]; then
        echo "Usage: set_aws_profile_and_update <profile_name>"
        return 1
    fi

    # Set the AWS_PROFILE environment variable
    export AWS_PROFILE="$1"
    echo "AWS_PROFILE set to $AWS_PROFILE"

    # rm /tmp/aws_env_cache

    # echo "Updating env variables"
    # eval "$(aws configure export-credentials --format env)"
    # Run the updateAws command
    echo "Refreshing env cache"
    updateAWSLoginCache.py --force $$
}


get_aws_profile() {

    updateAWSLoginCache.py $$ > /dev/null 2>&1 &

    # Check if the file exists
    if [[ -f "/tmp/aws_current_env_$$" ]]; then
        # Read the file's content
        echo "aws: $(cat /tmp/aws_current_env_$$)"
    else
        # Return 'ERROR' if the file does not exist
        echo "aws: refreshing..." 
    fi

}

setopt PROMPT_SUBST
PROMPT='$(get_aws_profile) %9c%{%F{green}%}$(parse_git_branch)%{%F{none}%} $ '


# PROMPT='%9c%{%F{green}%}$(parse_git_branch)%{%F{none}%} $ '